import UserNotifications

enum NotificationManager {
    static func scheduleTestNotification() {
        let content = UNMutableNotificationContent()
        content.title = "PillOverlay"
        content.body = "This is a local notification generated by the app."
        content.sound = .default

        let trigger = UNTimeIntervalNotificationTrigger(
            timeInterval: 5,
            repeats: false
        )

        let request = UNNotificationRequest(
            identifier: UUID().uuidString,
            content: content,
            trigger: trigger
        )

        UNUserNotificationCenter.current().add(request)
    }
}
